# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskcode_settings', '0001_initial'),
        ('casefolder', '0001_initial'),
        ('client', '0001_initial'),
        ('reference_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('Corporate', 'Corporate/Company'), ('Individual', 'Individual'), ('School', 'School'), ('Government', 'Government')], max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('Big Entity', 'Big Entity'), ('Small Entity', 'Small Entity')], max_length=15)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=25)),
                ('applicant_isinventor', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Inventors/Designers',
            },
        ),
        migrations.CreateModel(
            name='Matters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_id', models.CharField(blank=True, max_length=24)),
                ('matter_qrcode', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('referenceno', models.CharField(blank=True, max_length=30)),
                ('clientrefno', models.CharField(blank=True, max_length=60)),
                ('matterno', models.CharField(blank=True, max_length=30)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('matter_title', models.TextField(null=True)),
                ('lawyers_involve', models.CharField(blank=True, max_length=60, null=True)),
                ('opposing_counsel', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.appearance')),
                ('apptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.apptype')),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.casetype')),
                ('filed_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.courts')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.casefolder')),
                ('handling_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data')),
                ('matter_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.contact_person')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.natureofcase')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.status')),
            ],
            options={
                'verbose_name_plural': 'Engagements/Accounts',
            },
        ),
        migrations.CreateModel(
            name='Matter_Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.inventor')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Inventors/Designers',
            },
        ),
        migrations.CreateModel(
            name='Matter_ClassOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_description', models.TextField(blank=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('nice_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.classofgoods')),
            ],
            options={
                'verbose_name_plural': 'Matters Class Of Goods',
            },
        ),
        migrations.CreateModel(
            name='Matter_Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('main_applicant', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=10)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.applicant')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Matter Applicants',
            },
        ),
        migrations.CreateModel(
            name='IP_Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo_examiner', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REGISTERED', 'REGISTERED'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('RENEWAL', 'RENEWAL'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True)),
                ('parent_appno', models.CharField(blank=True, max_length=30)),
                ('parent_appdate', models.DateField(blank=True, null=True)),
                ('application_no', models.CharField(blank=True, max_length=30)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=30)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('ipc_appno', models.CharField(blank=True, max_length=25)),
                ('ipc_appdate', models.DateField(blank=True, null=True)),
                ('publication_reference', models.CharField(blank=True, max_length=30)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('priority_number', models.CharField(blank=True, max_length=25)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('priority_country_filing', models.CharField(blank=True, max_length=30)),
                ('pct_appno', models.CharField(blank=True, max_length=30)),
                ('pct_appdate', models.DateField(blank=True, null=True)),
                ('pct_publication', models.CharField(blank=True, max_length=30)),
                ('pct_pubdate', models.DateField(blank=True, null=True)),
                ('lng_interappln', models.CharField(blank=True, max_length=30)),
                ('lng_interpubln', models.CharField(blank=True, max_length=30)),
                ('claim_of_color', models.CharField(blank=True, max_length=30)),
                ('translation', models.CharField(blank=True, max_length=60)),
                ('disclaimer', models.CharField(blank=True, max_length=100)),
                ('type_of_mark', models.CharField(blank=True, choices=[('Word Mark', 'Word Mark'), ('Figurative Mark', 'Figurative Mark'), ('Figurative w/ Word Mark', 'Figurative w/ Word Mark'), ('Three-dimensional', 'Three-dimensional'), ('Collective Mark', 'Collective Mark')], max_length=30)),
                ('reason_withdrawn', models.CharField(blank=True, max_length=200)),
                ('date_of_Withdrawn', models.DateField(blank=True, null=True)),
                ('date_Of_PCTPriority', models.DateField(blank=True, null=True)),
                ('copyright_number', models.CharField(blank=True, max_length=30)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Other IP Information',
            },
        ),
        migrations.CreateModel(
            name='CPY_Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(blank=True, null=True)),
                ('place_of_creation', models.CharField(blank=True, max_length=100)),
                ('classification_of_work', models.TextField(blank=True)),
                ('submission', models.CharField(blank=True, choices=[('Local', 'Local'), ('Foreign', 'Foreign')], max_length=10)),
                ('registered', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=5)),
                ('registered_at', models.CharField(choices=[('IPOPHL', 'with IPOPHL'), ('NLP', 'with NLP')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'CopyRight Details',
            },
        ),
        migrations.CreateModel(
            name='AppDueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField(blank=True, null=True)),
                ('particulars', models.CharField(max_length=250)),
                ('date_complied', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('duecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskcode_settings.duecode')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Due Dates',
            },
        ),
    ]
