# Generated by Django 4.2.6 on 2023-11-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('source_evidence', models.TextField(blank=True)),
                ('evidence_description', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='Evidences/%Y/%m/%D/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Case Evidences',
            },
        ),
    ]
