# Generated by Django 4.2.6 on 2023-11-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0001_initial'),
        ('reference_lookup', '0001_initial'),
        ('matter', '0003_casedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_matter',
            name='apptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.apptype'),
        ),
        migrations.AlterField(
            model_name='matters',
            name='apptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.apptype'),
        ),
        migrations.AlterField(
            model_name='matters',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.casetype'),
        ),
        migrations.AlterField(
            model_name='matters',
            name='handling_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data'),
        ),
        migrations.AlterField(
            model_name='matters',
            name='matter_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matters',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.natureofcase'),
        ),
    ]
