# Generated by Django 4.2.6 on 2023-11-29 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0004_ip_matter_apptype_alter_matters_apptype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedescription',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casedescription',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
