# Generated by Django 4.2.6 on 2023-11-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0001_initial'),
        ('matter', '0005_casedescription_created_casedescription_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedescription',
            name='submittedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data'),
        ),
    ]
