# Generated by Django 4.2.6 on 2023-12-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0006_casedescription_submittedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_number', models.CharField(blank=True, max_length=25)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('priority_country_filing', models.CharField(blank=True, max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Convention Priorities',
            },
        ),
    ]
