# Generated by Django 4.2.6 on 2023-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0007_conventionpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionpriority',
            name='certified_copy_attached',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3),
        ),
    ]
