# Generated by Django 4.2.6 on 2023-12-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_lookup', '0001_initial'),
        ('matter', '0008_conventionpriority_certified_copy_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='matters',
            name='stage_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.activitygroup'),
        ),
    ]
