# Generated by Django 4.2.6 on 2023-12-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0009_matters_stage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter_applicant',
            name='main_applicant',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='IP_MatterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='IP_IMAGES/%Y/%m/%D/')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
        ),
    ]
