# Generated by Django 4.2.6 on 2024-01-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0010_alter_matter_applicant_main_applicant_ip_matterimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matters',
            name='matter_qrcode',
        ),
        migrations.AlterField(
            model_name='ip_matterimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='IP_IMAGES/%Y/'),
        ),
    ]
