# Generated by Django 4.2.6 on 2024-01-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0011_remove_matters_matter_qrcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedural_history', models.TextField(blank=True, null=True)),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
            options={
                'verbose_name_plural': 'Procedural History',
            },
        ),
    ]
