# Generated by Django 4.2.6 on 2024-01-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0012_casehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_matter',
            name='IR_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ip_matter',
            name='IR_renewalDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
