# Generated by Django 4.2.6 on 2024-01-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0013_ip_matter_ir_date_ip_matter_ir_renewaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_matterimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
