# Generated by Django 4.2.6 on 2024-01-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0015_ip_matterimage_created_ip_matterimage_docdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_matterimage',
            name='docimage',
            field=models.FileField(blank=True, null=True, upload_to='IP_IMAGES/%Y/'),
        ),
    ]
