# Generated by Django 4.2.6 on 2024-01-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0016_ip_matterimage_docimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_matterimage',
            name='docimage',
        ),
    ]
