# Generated by Django 4.2.6 on 2024-02-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0001_initial'),
        ('matter', '0017_remove_ip_matterimage_docimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matters',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='casefolder.casefolder'),
        ),
    ]
