# Generated by Django 4.2.6 on 2024-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0019_ip_matter_ir_subsequentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_matter',
            name='nice_class',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='TM_Image',
            field=models.ImageField(blank=True, null=True, upload_to='TM_IMAGE/'),
        ),
    ]
