# Generated by Django 4.2.6 on 2024-03-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0020_ip_matter_nice_class_matters_tm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='matters',
            name='IR_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='IR_renewalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='IR_subsequentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='application_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='claim_of_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='copyright_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='date_Of_PCTPriority',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='date_of_Withdrawn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matters',
            name='ipc_appdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='ipc_appno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='matters',
            name='ipo_examiner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matters',
            name='lng_interappln',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='lng_interpubln',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='nice_class',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='parent_appdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='parent_appno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='pct_appdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='pct_appno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='pct_pubdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='pct_publication',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='priority_country_filing',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='priority_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='priority_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='matters',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='publication_reference',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='matters',
            name='reason_withdrawn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='matters',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matters',
            name='translation',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='matters',
            name='type_of_mark',
            field=models.CharField(blank=True, choices=[('Word Mark', 'Word Mark'), ('Figurative Mark', 'Figurative Mark'), ('Figurative w/ Word Mark', 'Figurative w/ Word Mark'), ('Three-dimensional', 'Three-dimensional'), ('Collective Mark', 'Collective Mark')], max_length=30),
        ),
    ]
