# Generated by Django 4.2.6 on 2024-03-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0021_matters_ir_date_matters_ir_renewaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matters',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.applicant'),
        ),
    ]
