# Generated by Django 4.2.6 on 2024-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0022_matters_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMatters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
        ),
    ]
