# Generated by Django 4.2.6 on 2024-08-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0002_remove_lawyer_data_profile_pic'),
        ('matter', '0023_selectmatters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party1', models.TextField(blank=True, null=True)),
                ('position_1', models.CharField(blank=True, max_length=100, null=True)),
                ('party2', models.TextField(blank=True, null=True)),
                ('position_2', models.CharField(blank=True, max_length=100, null=True)),
                ('opposing_counsel', models.TextField(blank=True, max_length=100, null=True)),
                ('firms_counsel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
        ),
    ]
