# Generated by Django 4.2.6 on 2024-09-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0024_matterlitigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matterlitigation',
            options={'verbose_name_plural': 'Engagement - Litigation'},
        ),
    ]
