# Generated by Django 4.2.6 on 2024-10-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0025_alter_matterlitigation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventor',
            options={'verbose_name_plural': 'List Of Inventors'},
        ),
        migrations.AlterModelOptions(
            name='matter_applicant',
            options={'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='matter_inventor',
            options={'verbose_name_plural': 'Matter Inventors'},
        ),
        migrations.AlterModelOptions(
            name='matterlitigation',
            options={'verbose_name_plural': 'Engagement-Non-IP'},
        ),
        migrations.AlterModelOptions(
            name='matters',
            options={'verbose_name_plural': 'Engagements'},
        ),
    ]
