# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefolder', '0001_initial'),
        ('client', '0001_initial'),
        ('reference_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DueCode', models.CharField(blank=True, max_length=20)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('basisofcompute', models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True)),
                ('fieldbsis', models.CharField(blank=True, choices=[('Application Date', 'Application Date'), ('Renewal Date', 'Renewal Date'), ('Publication Date', 'PublicationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Registration Date', 'RegistrationDate'), ('Document Date', 'Document Date'), ('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Priority Date', 'Priority Date'), ('PCT Filing Date', 'PCT Filing Date')], max_length=30, null=True)),
                ('terms', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('apptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.apptype')),
                ('folder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityCode', models.CharField(blank=True, max_length=15)),
                ('TranType', models.CharField(blank=True, choices=[('BILLABLE', 'BILLABLE'), ('MAILSIN', 'MAILSIN')], max_length=15, null=True)),
                ('seqorder', models.IntegerField(blank=True, null=True)),
                ('Activity', models.CharField(max_length=250)),
                ('bill_description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pesorate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pesoamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.currency')),
                ('foldertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
        ),
    ]
