# Generated by Django 4.2.6 on 2023-11-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0006_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycodes',
            options={'verbose_name_plural': 'Task/Activity Codes'},
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Days', 'In Days'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Receipt Date', 'Document Receipt Date'), ('PCT Filing Date', 'PCT Filing Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('Renewal Date', 'Renewal Date'), ('Document Date', 'Document Date'), ('Publication Date', 'PublicationDate'), ('Priority Date', 'Priority Date')], max_length=30, null=True),
        ),
    ]
