# Generated by Django 4.2.6 on 2023-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0007_alter_activitycodes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'Document Date'), ('Renewal Date', 'Renewal Date'), ('Application Date', 'Application Date'), ('Priority Date', 'Priority Date'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Publication Date', 'PublicationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Registration Date', 'RegistrationDate')], max_length=30, null=True),
        ),
    ]
