# Generated by Django 4.2.6 on 2024-01-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0019_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('BILLABLE', 'BILLABLE'), ('MAILSIN', 'MAILSIN')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'Document Date'), ('Registration Date', 'RegistrationDate'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Renewal Date', 'Renewal Date'), ('Application Date', 'Application Date'), ('Publication Date', 'PublicationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('Priority Date', 'Priority Date'), ('PCT Publication Date', 'PCT Publication Date')], max_length=30, null=True),
        ),
    ]
