# Generated by Django 4.2.6 on 2024-01-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_data_billing_address_and_more'),
        ('taskcode_settings', '0022_alter_activitycodes_trantype_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('MAILSIN', 'MAILSIN'), ('BILLABLE', 'BILLABLE')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Days', 'In Days'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('Registration Date', 'RegistrationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Date', 'Document Date')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='FilingFeeCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeeCode', models.CharField(blank=True, max_length=15)),
                ('fee_description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pesorate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pesoamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ActivityCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskcode_settings.activitycodes')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.currency')),
            ],
        ),
    ]
