# Generated by Django 4.2.6 on 2024-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0032_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('MAILSIN', 'MAILSIN'), ('BILLABLE', 'BILLABLE')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Filing Date', 'PCT Filing Date'), ('Priority Date', 'Priority Date'), ('Renewal Date', 'Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Registration Date', 'RegistrationDate'), ('IR Date', 'IR Date'), ('Publication Date', 'PublicationDate'), ('RunDate', 'RunDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Document Date', 'Document Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Application Date', 'Application Date')], max_length=30, null=True),
        ),
    ]
