# Generated by Django 4.2.6 on 2024-02-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0038_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('BILLABLE', 'BILLABLE'), ('MAILSIN', 'MAILSIN')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'Document Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Application Date', 'Application Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Renewal Date', 'Renewal Date'), ('RunDate', 'RunDate'), ('Priority Date', 'Priority Date'), ('Publication Date', 'PublicationDate'), ('IR Date', 'IR Date'), ('IR Renewal Date', 'IR Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Registration Date', 'RegistrationDate')], max_length=30, null=True),
        ),
    ]
