# Generated by Django 4.2.6 on 2024-02-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0043_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Registration Date', 'RegistrationDate'), ('Application Date', 'Application Date'), ('IR Date', 'IR Date'), ('Priority Date', 'Priority Date'), ('Renewal Date', 'Renewal Date'), ('RunDate', 'RunDate'), ('PCT Filing Date', 'PCT Filing Date'), ('Publication Date', 'PublicationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Document Date', 'Document Date'), ('IR Renewal Date', 'IR Renewal Date')], max_length=30, null=True),
        ),
    ]
