# Generated by Django 4.2.6 on 2024-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0045_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Priority Date', 'Priority Date'), ('Registration Date', 'RegistrationDate'), ('IR Renewal Date', 'IR Renewal Date'), ('PCT Filing Date', 'PCT Filing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Application Date', 'Application Date'), ('Document Date', 'Document Date'), ('OA Mailing Date', 'OA Mailing Date'), ('RunDate', 'RunDate'), ('Document Receipt Date', 'Document Receipt Date'), ('IR Date', 'IR Date'), ('Publication Date', 'PublicationDate'), ('Renewal Date', 'Renewal Date')], max_length=30, null=True),
        ),
    ]
