# Generated by Django 4.2.6 on 2024-02-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0047_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('BILLABLE', 'BILLABLE'), ('MAILSIN', 'MAILSIN')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('RunDate', 'RunDate'), ('IR Date', 'IR Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR Renewal Date', 'IR Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Renewal Date', 'Renewal Date'), ('Publication Date', 'PublicationDate'), ('Document Date', 'Document Date'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('Priority Date', 'Priority Date')], max_length=30, null=True),
        ),
    ]
