# Generated by Django 4.2.6 on 2024-02-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0048_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('IR Renewal Date', 'IR Renewal Date'), ('RunDate', 'RunDate'), ('Priority Date', 'Priority Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Publication Date', 'PublicationDate'), ('IR Date', 'IR Date'), ('Registration Date', 'RegistrationDate'), ('Application Date', 'Application Date'), ('Document Date', 'Document Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Renewal Date', 'Renewal Date')], max_length=30, null=True),
        ),
    ]
