# Generated by Django 4.2.6 on 2024-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0054_alter_activitycodes_trantype_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Days', 'In Days'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Priority Date', 'Priority Date'), ('Application Date', 'Application Date'), ('Renewal Date', 'Renewal Date'), ('IR Date', 'IR Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Registration Date', 'RegistrationDate'), ('Document Date', 'Document Date'), ('Publication Date', 'PublicationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('RunDate', 'RunDate'), ('OA Mailing Date', 'OA Mailing Date')], max_length=30, null=True),
        ),
    ]
