# Generated by Django 4.2.6 on 2024-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0058_alter_activitycodes_trantype_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Receipt Date', 'Document Receipt Date'), ('Publication Date', 'PublicationDate'), ('Priority Date', 'Priority Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Application Date', 'Application Date'), ('OA Mailing Date', 'OA Mailing Date'), ('IR Date', 'IR Date'), ('Renewal Date', 'Renewal Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Registration Date', 'RegistrationDate'), ('Document Date', 'Document Date'), ('PCT Filing Date', 'PCT Filing Date'), ('RunDate', 'RunDate')], max_length=30, null=True),
        ),
    ]
