# Generated by Django 4.2.6 on 2024-03-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0060_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('PCT Publication Date', 'PCT Publication Date'), ('OA Mailing Date', 'OA Mailing Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Document Date', 'Document Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Application Date', 'Application Date'), ('RunDate', 'RunDate'), ('IR Date', 'IR Date'), ('Registration Date', 'RegistrationDate'), ('Publication Date', 'PublicationDate'), ('Document Receipt Date', 'Document Receipt Date')], max_length=30, null=True),
        ),
    ]
