# Generated by Django 4.2.6 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0071_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Filing Date', 'PCT Filing Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('IR Renewal Date', 'IR Renewal Date'), ('Application Date', 'Application Date'), ('RunDate', 'RunDate'), ('Renewal Date', 'Renewal Date'), ('Document Date', 'Document Date'), ('Registration Date', 'RegistrationDate'), ('IR Date', 'IR Date'), ('Priority Date', 'Priority Date'), ('PCT Publication Date', 'PCT Publication Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Publication Date', 'PublicationDate')], max_length=30, null=True),
        ),
    ]
