# Generated by Django 4.2.6 on 2024-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0088_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Application Date', 'Application Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Priority Date', 'Priority Date'), ('Registration Date', 'RegistrationDate'), ('IR Date', 'IR Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Date', 'Document Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR Renewal Date', 'IR Renewal Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Renewal Date', 'Renewal Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Publication Date', 'PublicationDate'), ('RunDate', 'RunDate')], max_length=30, null=True),
        ),
    ]
