# Generated by Django 4.2.6 on 2024-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0090_alter_duecode_basisofcompute_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Days', 'In Days'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Publication Date', 'PCT Publication Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('IR Date', 'IR Date'), ('Publication Date', 'PublicationDate'), ('Renewal Date', 'Renewal Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Priority Date', 'Priority Date'), ('Application Date', 'Application Date'), ('RunDate', 'RunDate')], max_length=30, null=True),
        ),
    ]
