# Generated by Django 4.2.6 on 2024-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0092_alter_activitycodes_trantype_alter_duecode_fieldbsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('Application Date', 'Application Date'), ('IR Date', 'IR Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('IR Renewal Date', 'IR Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Publication Date', 'PublicationDate'), ('Renewal Date', 'Renewal Date'), ('RunDate', 'RunDate'), ('Priority Date', 'Priority Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Registration Date', 'RegistrationDate')], max_length=30, null=True),
        ),
    ]
