# Generated by Django 4.2.6 on 2024-03-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_lookup', '0003_activitygroup_seq'),
        ('casefolder', '0002_remove_lawyer_data_profile_pic'),
        ('taskcode_settings', '0094_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Days', 'In Days'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('IR Renewal Date', 'IR Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('IR Date', 'IR Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Document Date', 'Document Date'), ('Publication Date', 'PublicationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Renewal Date', 'Renewal Date'), ('RunDate', 'RunDate'), ('PCT Filing Date', 'PCT Filing Date'), ('Registration Date', 'RegistrationDate'), ('Priority Date', 'Priority Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Application Date', 'Application Date')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DueCode_Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DueCode', models.CharField(blank=True, max_length=20)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('basisofcompute', models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Days', 'In Days'), ('In Months', 'In Months')], max_length=15, null=True)),
                ('fieldbsis', models.CharField(blank=True, choices=[('Mailing Date', 'mailing_date'), ('Date Receipt', 'tran_date'), ('Document Date', 'doc_date')], max_length=30, null=True)),
                ('terms', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('apptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.apptype')),
                ('folder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
        ),
    ]
