# Generated by Django 4.2.6 on 2024-07-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0107_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('IR Date', 'IR Date'), ('Registration Date', 'RegistrationDate'), ('Document Date', 'Document Date'), ('IR Renewal Date', 'IR Renewal Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Priority Date', 'Priority Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Application Date', 'Application Date'), ('RunDate', 'RunDate'), ('Renewal Date', 'Renewal Date'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Publication Date', 'PublicationDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Date Receipt', 'tran_date'), ('Document Date', 'doc_date'), ('Mailing Date', 'mailing_date')], max_length=30, null=True),
        ),
    ]
