# Generated by Django 4.2.6 on 2024-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0109_alter_duecode_basisofcompute_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('RunDate', 'RunDate'), ('Application Date', 'Application Date'), ('IR Renewal Date', 'IR Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('Priority Date', 'Priority Date'), ('Publication Date', 'PublicationDate'), ('Document Date', 'Document Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Renewal Date', 'Renewal Date'), ('IR Date', 'IR Date'), ('PCT Filing Date', 'PCT Filing Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'doc_date'), ('Date Receipt', 'tran_date'), ('Mailing Date', 'mailing_date')], max_length=30, null=True),
        ),
    ]
