# Generated by Django 4.2.6 on 2024-07-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0114_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('IR Renewal Date', 'IR Renewal Date'), ('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Publication Date', 'PCT Publication Date'), ('RunDate', 'RunDate'), ('Renewal Date', 'Renewal Date'), ('IR Date', 'IR Date'), ('Document Date', 'Document Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Priority Date', 'Priority Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'doc_date'), ('Mailing Date', 'mailing_date'), ('Date Receipt', 'tran_date')], max_length=30, null=True),
        ),
    ]
