# Generated by Django 4.2.6 on 2024-07-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0116_alter_duecode_basisofcompute_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('RunDate', 'RunDate'), ('Application Date', 'Application Date'), ('OA Mailing Date', 'OA Mailing Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Priority Date', 'Priority Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('Document Receipt Date', 'Document Receipt Date'), ('IR Renewal Date', 'IR Renewal Date'), ('IR Date', 'IR Date'), ('Publication Date', 'PublicationDate'), ('Renewal Date', 'Renewal Date'), ('Registration Date', 'RegistrationDate'), ('PCT Publication Date', 'PCT Publication Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Mailing Date', 'mailing_date'), ('Date Receipt', 'tran_date'), ('Document Date', 'doc_date')], max_length=30, null=True),
        ),
    ]
