# Generated by Django 4.2.6 on 2024-07-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0120_alter_duecode_basisofcompute_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Days', 'In Days'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Registration Date', 'RegistrationDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Renewal Date', 'Renewal Date'), ('Application Date', 'Application Date'), ('Document Receipt Date', 'Document Receipt Date'), ('RunDate', 'RunDate'), ('IR Renewal Date', 'IR Renewal Date'), ('Publication Date', 'PublicationDate'), ('Document Date', 'Document Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Priority Date', 'Priority Date'), ('IR Date', 'IR Date'), ('PCT Publication Date', 'PCT Publication Date'), ('PCT Filing Date', 'PCT Filing Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Days', 'In Days'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Date', 'doc_date'), ('Date Receipt', 'tran_date'), ('Mailing Date', 'mailing_date')], max_length=30, null=True),
        ),
    ]
