# Generated by Django 4.2.6 on 2024-07-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0121_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Filing Date', 'PCT Filing Date'), ('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR Date', 'IR Date'), ('Document Date', 'Document Date'), ('RunDate', 'RunDate'), ('IR Renewal Date', 'IR Renewal Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('OA Mailing Date', 'OA Mailing Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Mailing Date', 'mailing_date'), ('Document Date', 'doc_date'), ('Date Receipt', 'tran_date')], max_length=30, null=True),
        ),
    ]
