# Generated by Django 4.2.6 on 2024-07-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0123_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Publication Date', 'PublicationDate'), ('RunDate', 'RunDate'), ('PCT Filing Date', 'PCT Filing Date'), ('Registration Date', 'RegistrationDate'), ('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Application Date', 'Application Date'), ('Document Receipt Date', 'Document Receipt Date'), ('IR Date', 'IR Date'), ('IR Renewal Date', 'IR Renewal Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Document Date', 'Document Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Date Receipt', 'tran_date'), ('Mailing Date', 'mailing_date'), ('Document Date', 'doc_date')], max_length=30, null=True),
        ),
    ]
