# Generated by Django 4.2.6 on 2024-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0125_alter_duecode_basisofcompute_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('RunDate', 'RunDate'), ('Renewal Date', 'Renewal Date'), ('Application Date', 'Application Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Registration Date', 'RegistrationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('IR Renewal Date', 'IR Renewal Date'), ('IR Date', 'IR Date'), ('Priority Date', 'Priority Date'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('Publication Date', 'PublicationDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Date Receipt', 'tran_date'), ('Mailing Date', 'mailing_date'), ('Document Date', 'doc_date')], max_length=30, null=True),
        ),
    ]
