# Generated by Django 4.2.6 on 2024-07-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0139_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycodes',
            name='TranType',
            field=models.CharField(blank=True, choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Priority Date', 'Priority Date'), ('Document Date', 'Document Date'), ('Renewal Date', 'Renewal Date'), ('Document Receipt Date', 'Document Receipt Date'), ('IR Renewal Date', 'IR Renewal Date'), ('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('IR Date', 'IR Date'), ('Registration Date', 'RegistrationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('RunDate', 'RunDate'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('IR_subsequentDate', 'IR_subsequentDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
    ]
