# Generated by Django 4.2.6 on 2024-08-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcode_settings', '0141_alter_activitycodes_trantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('OA Mailing Date', 'OA Mailing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('RunDate', 'RunDate'), ('Renewal Date', 'Renewal Date'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('IR Renewal Date', 'IR Renewal Date'), ('PCT Publication Date', 'PCT Publication Date'), ('IR_subsequentDate', 'IR_subsequentDate'), ('IR Date', 'IR Date'), ('Priority Date', 'Priority Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('Publication Date', 'PublicationDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode_incoming',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
    ]
