# Generated by Django 4.2.6 on 2024-02-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxmessage',
            name='messagedate',
        ),
    ]
