# Generated by Django 4.2.6 on 2024-02-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0005_alter_inboxmessage_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxmessage',
            options={'verbose_name_plural': 'Sent Messages'},
        ),
        migrations.AlterModelOptions(
            name='tempchatmessages',
            options={'verbose_name_plural': 'Chat Message'},
        ),
    ]
