# Generated by Django 4.2.6 on 2023-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='billing_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client_data',
            name='billing_attention',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='client_data',
            name='billing_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client_data',
            name='position',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
