# Generated by Django 4.2.6 on 2024-02-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_data_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_person',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
