# Generated by Django 4.2.6 on 2024-02-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_contact_person_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
    ]
