# Generated by Django 4.2.6 on 2024-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_currency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='account_officer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='account_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='client_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='client_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='entered_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='fax_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='unit_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_data',
            name='website',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
