# Generated by Django 4.2.6 on 2024-03-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_data_account_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_data',
            name='category',
        ),
    ]
