# Generated by Django 4.2.6 on 2024-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_data_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='updatedby',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
