# Generated by Django 4.2.6 on 2024-07-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_client_data_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
