# Generated by Django 4.2.6 on 2024-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_client_data_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
