# Generated by Django 4.2.6 on 2024-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_client_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='landline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
