# Generated by Django 4.2.6 on 2024-07-26 19:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_client_data_landline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
