# Generated by Django 4.2.6 on 2024-07-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_client_data_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_data',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_data',
            name='country_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
