# Generated by Django 4.2.6 on 2024-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_client_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureofbusiness',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
