# Generated by Django 4.2.6 on 2024-07-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_alter_natureofbusiness_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureofbusiness',
            name='ipw_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
