# Generated by Django 4.2.6 on 2024-07-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_natureofbusiness_ipw_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
