# Generated by Django 4.2.6 on 2024-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_alter_contact_person_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone/Mobile #'),
        ),
    ]
