# Generated by Django 4.2.6 on 2024-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMwatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Number', models.CharField(blank=True, max_length=25, null=True)),
                ('Filing_Date', models.CharField(blank=True, max_length=40, null=True)),
                ('Mark', models.CharField(blank=True, max_length=150, null=True)),
                ('Applicant', models.CharField(blank=True, max_length=150, null=True)),
                ('Nice_class', models.CharField(blank=True, max_length=150, null=True)),
                ('myClient_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('myApplicationNo', models.CharField(blank=True, max_length=25, null=True)),
                ('myPatAppNo', models.CharField(blank=True, max_length=30, null=True)),
                ('myApplicationDate', models.DateField(blank=True, null=True)),
                ('myApplicant', models.CharField(blank=True, max_length=200, null=True)),
                ('myClientRefNo', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
