# Generated by Django 4.2.6 on 2024-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmwatch', '0002_tmwatchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmwatchresult',
            name='myCase1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
