# Generated by Django 4.2.6 on 2024-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmwatch', '0003_tmwatchresult_mycase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmwatchresult',
            name='my_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
