# Generated by Django 4.2.6 on 2024-02-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0018_alter_matters_folder'),
        ('emailportal', '0002_emails_sentby_alter_emails_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.matters'),
        ),
    ]
