# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefolder', '0001_initial'),
        ('taskcode_settings', '0001_initial'),
        ('matter', '0001_initial'),
        ('reference_lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('doc_type', models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Others', 'Others')], max_length=20, null=True)),
                ('tran_type', models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True)),
                ('task', models.TextField()),
                ('spentinhrs', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('spentinmin', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('mailing_date', models.DateField(blank=True, null=True)),
                ('examiner', models.CharField(blank=True, max_length=60, null=True)),
                ('mail_type', models.CharField(blank=True, choices=[('IPO', 'IPO'), ('Email', 'Email'), ('Court', 'Court'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50)),
                ('billstatus', models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Unbilled', 'Unbilled')], default='Unbilled', max_length=15, null=True)),
                ('createdby', models.CharField(blank=True, max_length=30, null=True)),
                ('updatedby', models.CharField(blank=True, max_length=30, null=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('duecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taskcode_settings.duecode')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('stage_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_lookup.activitygroup')),
                ('task_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskcode_settings.activitycodes')),
            ],
        ),
    ]
