# Generated by Django 4.2.6 on 2023-11-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filingdocs',
            options={'verbose_name_plural': 'Attached Documents'},
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Unbilled', 'Unbilled'), ('Billed', 'Billed')], default='Unbilled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Others', 'Others'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Court', 'Court'), ('Email', 'Email'), ('IPO', 'IPO'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
    ]
