# Generated by Django 4.2.6 on 2023-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Unbilled', 'Unbilled'), ('Billed', 'Billed')], default='Unbilled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('IPO', 'IPO'), ('Personal', 'Personal'), ('Court', 'Court'), ('Email', 'Email'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
    ]
