# Generated by Django 4.2.6 on 2024-01-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_alter_task_detail_billstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Email', 'Email'), ('IPO', 'IPO'), ('Mail', 'Mail'), ('Court', 'Court')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
    ]
