# Generated by Django 4.2.6 on 2024-01-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('IPO', 'IPO'), ('Email', 'Email'), ('Court', 'Court'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
    ]
