# Generated by Django 4.2.6 on 2024-01-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingdocs',
            name='DocsPDF',
            field=models.FileField(blank=True, null=True, upload_to='Documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Unbilled', 'Unbilled'), ('Billed', 'Billed')], default='Unbilled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Mail', 'Mail'), ('Court', 'Court'), ('Personal', 'Personal'), ('IPO', 'IPO')], max_length=15, null=True),
        ),
    ]
