# Generated by Django 4.2.6 on 2024-02-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0045_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Outgoing', 'Outgoing'), ('Incoming', 'Incoming'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Court', 'Court'), ('Mail', 'Mail'), ('IPO', 'IPO'), ('Personal', 'Personal'), ('Email', 'Email')], max_length=15, null=True),
        ),
    ]
