# Generated by Django 4.2.6 on 2024-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0059_alter_task_detail_billstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('IPO', 'IPO'), ('Email', 'Email'), ('Court', 'Court'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
    ]
