# Generated by Django 4.2.6 on 2024-03-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0079_alter_task_detail_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Unbilled', 'Unbilled'), ('Billed', 'Billed')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('IPO', 'IPO'), ('Email', 'Email'), ('Mail', 'Mail'), ('Court', 'Court')], max_length=15, null=True),
        ),
    ]
