# Generated by Django 4.2.6 on 2024-04-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0103_alter_task_detail_billstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('IPO', 'IPO'), ('Court', 'Court'), ('Mail', 'Mail'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
    ]
