# Generated by Django 4.2.6 on 2024-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0109_alter_task_detail_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Email', 'Email'), ('Court', 'Court'), ('IPO', 'IPO'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
    ]
