# Generated by Django 4.2.6 on 2024-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0130_alter_task_detail_billstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Unbilled', 'Unbilled')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Outgoing', 'Outgoing'), ('Incoming', 'Incoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Court', 'Court'), ('IPO', 'IPO'), ('Email', 'Email'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
    ]
