# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('rank', models.CharField(choices=[('MANAGING PARTNER', 'MANAGING PARTNER'), ('PARTNER', 'PARTNER'), ('ASSOCIATES', 'ASSOCIATES'), ('SECRETARY', 'SECRETARY'), ('PARALEGAL', 'PARALEGAL'), ('MIS STAFF', 'MIS STAFF'), ('SYSTEM ADMIN', 'SYSTEM ADMIN'), ('ACCOUNTING STAFF', 'ACCOUNTING STAFF'), ('DATA ENCODER', 'DATA ENCODER'), ('FRONTEND DEVELOPER', 'FRONTEND DEVELOPER'), ('BACKEND DEVELOPER', 'BACKEND DEVELOPER'), ('SYSTEM DEVELOPER', 'SYSTEM DEVELOPER'), ('CLIENT', 'CLIENT')], max_length=30, null=True)),
                ('access_code', models.CharField(blank=True, max_length=5, null=True)),
                ('supporto', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile', models.CharField(max_length=60, null=True)),
                ('image', models.ImageField(blank=True, upload_to='Profile_Images/')),
                ('remarks', models.TextField(null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('userid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
