# Generated by Django 4.2.6 on 2024-02-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_ResidentAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentnumber', models.CharField(blank=True, max_length=30, null=True)),
                ('companyname', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Femail', 'Female')], max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('town', models.CharField(blank=True, max_length=60, null=True)),
                ('province', models.CharField(blank=True, max_length=60, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('contactno', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
