# Generated by Django 4.2.6 on 2024-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, null=True, upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='csv_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTNUMBER', models.CharField(blank=True, max_length=25, null=True)),
                ('EntityType', models.CharField(blank=True, max_length=15, null=True)),
                ('ClientName', models.CharField(blank=True, max_length=200, null=True)),
                ('UnitDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Street', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State_Prov', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=25, null=True)),
                ('Fax_Number', models.CharField(blank=True, max_length=60, null=True)),
                ('EMail', models.CharField(blank=True, max_length=100, null=True)),
                ('URL', models.CharField(blank=True, max_length=60, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=25, null=True)),
                ('Telephone_Number', models.CharField(blank=True, max_length=60, null=True)),
                ('CountryCode', models.CharField(blank=True, max_length=25, null=True)),
                ('Industry', models.CharField(blank=True, max_length=100, null=True)),
                ('ClientType', models.CharField(blank=True, max_length=25, null=True)),
                ('AccountOfficer', models.CharField(blank=True, max_length=60, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
