# Generated by Django 4.2.6 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0004_csv_matter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_matter',
            name='Case1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='csv_matter',
            name='Case2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
