# Generated by Django 4.2.6 on 2024-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0005_alter_csv_matter_case1_alter_csv_matter_case2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_matter',
            old_name='ClaimingColor',
            new_name='Remarks',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='ExamFee',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='KeyWords',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='LedesMatterID',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='MultipleDependencies',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='NoticeOfAllowance',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='NumberOfDependencies',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='OrderNewFiling',
        ),
        migrations.RemoveField(
            model_name='csv_matter',
            name='PatenTee',
        ),
        migrations.AddField(
            model_name='csv_client',
            name='ClientOf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='csv_client',
            name='DateEntered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csv_client',
            name='Date_Acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csv_client',
            name='ModifiedBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='csv_client',
            name='AccountOfficer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csv_client',
            name='ClientType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
