# Generated by Django 4.2.6 on 2024-03-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0006_rename_claimingcolor_csv_matter_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_matter',
            name='WithPriority',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
