# Generated by Django 4.2.6 on 2024-03-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0009_csv_duedates'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_AR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('ApplicationNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BillNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('BillDate', models.DateField(blank=True, null=True)),
                ('BillAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PesoAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EuroAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PaymentTag', models.CharField(blank=True, max_length=5, null=True)),
                ('ORNumber1', models.CharField(blank=True, max_length=10, null=True)),
                ('ORDate1', models.DateField(blank=True, null=True)),
                ('AmountPaid1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CheckNumber1', models.CharField(blank=True, max_length=30, null=True)),
                ('CheckDate1', models.DateField(blank=True, null=True)),
                ('ORNumber2', models.CharField(blank=True, max_length=10, null=True)),
                ('ORDate2', models.DateField(blank=True, null=True)),
                ('AmountPaid2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CheckNumber2', models.CharField(blank=True, max_length=30, null=True)),
                ('CheckDate2', models.DateField(blank=True, null=True)),
                ('ORNumber3', models.CharField(blank=True, max_length=10, null=True)),
                ('ORDate3', models.DateField(blank=True, null=True)),
                ('AmountPaid3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CheckNumber3', models.CharField(blank=True, max_length=30, null=True)),
                ('CheckDate3', models.DateField(blank=True, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=60, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('DisCount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PF', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('FILINGFEES', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OPE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('PesoRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('StampID', models.CharField(blank=True, max_length=60, null=True)),
                ('ModifiedBy', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
