# Generated by Django 4.2.6 on 2024-07-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0010_csv_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_client',
            name='Country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
