# Generated by Django 4.2.6 on 2024-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0011_alter_csv_client_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_casefolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_description', models.CharField(max_length=200)),
                ('folder_type', models.CharField(blank=True, max_length=25, null=True)),
                ('Supervisinglawyer', models.CharField(blank=True, max_length=25, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
