# Generated by Django 4.2.6 on 2024-07-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0012_csv_casefolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_matter',
            name='Renewal',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
