# Generated by Django 4.2.6 on 2024-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0013_alter_csv_matter_renewal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv_casefolder',
            old_name='Supervisinglawyer',
            new_name='clientnumber',
        ),
        migrations.AddField(
            model_name='csv_casefolder',
            name='Supervising_lawyer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csv_casefolder',
            name='folder_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv_casefolder',
            name='client_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
