# Generated by Django 4.2.6 on 2024-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0014_rename_supervisinglawyer_csv_casefolder_clientnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_casefolder',
            name='Supervising_lawyer_id',
        ),
        migrations.RemoveField(
            model_name='csv_casefolder',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='csv_casefolder',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='csv_casefolder',
            name='folder_type_id',
        ),
        migrations.RemoveField(
            model_name='csv_casefolder',
            name='remarks',
        ),
    ]
