# Generated by Django 4.2.6 on 2024-07-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0015_remove_csv_casefolder_supervising_lawyer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_apptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationType', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
