# Generated by Django 4.2.6 on 2024-07-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0016_csv_apptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_appstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppStat', models.CharField(blank=True, max_length=10)),
                ('ApplicationStatus', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
