# Generated by Django 4.2.6 on 2024-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0023_remove_csv_templates_operation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(blank=True, max_length=10)),
                ('Description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
