# Generated by Django 4.2.6 on 2024-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0024_csv_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
