# Generated by Django 4.2.6 on 2024-07-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0025_csv_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_clientfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_number', models.CharField(max_length=15)),
                ('entity_type', models.CharField(blank=True, max_length=15)),
                ('category', models.CharField(blank=True, max_length=15)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('unit_description', models.CharField(blank=True, max_length=60)),
                ('street', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('country_name', models.CharField(blank=True, max_length=60)),
                ('fax_number', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=60)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('landline', models.CharField(blank=True, max_length=100)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('industry_id', models.IntegerField(blank=True, null=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(blank=True, max_length=10)),
                ('account_officer', models.CharField(blank=True, max_length=50)),
                ('account_person', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
