# Generated by Django 4.2.6 on 2024-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconversion', '0027_alter_csv_clientfile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_clientfile',
            name='account_officer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='account_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='client_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='client_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='country_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='entity_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='fax_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='landline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='unit_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='website',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='csv_clientfile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
