# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casefolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_group', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stage Group',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appearance',
            },
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptype', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Types Of IP Applications',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Case Type',
            },
        ),
        migrations.CreateModel(
            name='ClassOFGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nice_class', models.PositiveSmallIntegerField()),
                ('class_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Nice Classification Of Goods',
            },
        ),
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('presiding_judge', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courts',
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_seq', models.IntegerField(blank=True, null=True)),
                ('Stages', models.CharField(max_length=60)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casefolder.foldertype')),
            ],
            options={
                'verbose_name_plural': 'Activity Group',
            },
        ),
        migrations.CreateModel(
            name='NatureOfCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('casetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_lookup.casetype')),
            ],
            options={
                'verbose_name_plural': 'Natures Of Cases',
            },
        ),
    ]
