# Generated by Django 4.2.6 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_lookup', '0002_activitygroup_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygroup',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
