# Generated by Django 4.2.6 on 2024-02-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0001_initial'),
        ('docutemplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='templatedocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('template_docname', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
        ),
        migrations.DeleteModel(
            name='templatesdoc',
        ),
    ]
