# Generated by Django 4.2.6 on 2024-03-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docutemplates', '0002_templatedocs_delete_templatesdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocs',
            name='filename',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
