# Generated by Django 4.2.6 on 2024-03-31 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0022_matters_applicant'),
        ('docutemplates', '0003_templatedocs_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='renderedtemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docutemplates.templatedocs')),
            ],
        ),
    ]
