# Generated by Django 4.2.6 on 2024-04-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docutemplates', '0004_renderedtemplates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='renderedtemplates',
        ),
    ]
