# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Folder Type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=60)),
                ('access_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=100)),
                ('hourlyrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('IBPRollNo', models.CharField(blank=True, max_length=40, null=True)),
                ('IBPChapter', models.CharField(blank=True, max_length=35, null=True)),
                ('IBPLifetimeNo', models.CharField(blank=True, max_length=35, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('remarks', models.CharField(max_length=200)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lawyerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Lawyers',
            },
        ),
        migrations.CreateModel(
            name='CaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_description', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Supervisinglawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.lawyer_data')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client_data')),
                ('folder_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casefolder.foldertype')),
            ],
            options={
                'verbose_name_plural': 'Case Folders',
            },
        ),
    ]
