# Generated by Django 4.2.6 on 2024-02-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casefolder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer_data',
            name='profile_pic',
        ),
    ]
