# Generated by Django 4.2.6 on 2023-11-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('matter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=15)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total_USDamount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_PhPamount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pf_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ope_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('peso_rate_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_tag', models.CharField(blank=True, choices=[('UN', 'Unpaid'), ('CN', 'Cancelled'), ('PP', 'Partially Paid'), ('WV', 'Waived'), ('CN', 'Cancelled'), ('WO', 'Write-Off')], default='UN', max_length=15)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_rendered', models.TextField(blank=True)),
                ('spentinhrs', models.IntegerField(blank=True, null=True)),
                ('spentinmin', models.IntegerField(blank=True, null=True)),
                ('pf_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.accountsreceivable')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.task_detail')),
            ],
        ),
        migrations.CreateModel(
            name='TempBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('service_rendered', models.TextField(blank=True, max_length=250)),
                ('spentinhrs', models.IntegerField(blank=True, null=True)),
                ('spentinmin', models.IntegerField(blank=True, null=True)),
                ('USDamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhPamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Proforma', 'Proforma'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled'), ('Waived', 'Waived')], default='Open', max_length=15)),
                ('recordedby', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.task_detail')),
            ],
            options={
                'verbose_name_plural': 'Temporary Billing Services',
            },
        ),
        migrations.CreateModel(
            name='TempOPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('expnse_particulars', models.CharField(blank=True, max_length=250, null=True)),
                ('USDamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhPamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled'), ('Waived', 'Waived')], default='Open', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.tempbills')),
            ],
        ),
        migrations.CreateModel(
            name='TempFilingFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('filing_particulars', models.CharField(blank=True, max_length=250, null=True)),
                ('USDamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhPamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Proforma', 'Proforma'), ('Billed', 'Billed'), ('Cancelled', 'Cancelled'), ('Waived', 'Waived')], default='Open', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.matters')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.tempbills')),
            ],
        ),
        migrations.CreateModel(
            name='OPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_particulars', models.TextField(blank=True)),
                ('exp_USDAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exp_PHPAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.accountsreceivable')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.task_detail')),
            ],
        ),
        migrations.CreateModel(
            name='FilingFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_particulars', models.TextField(blank=True)),
                ('filing_fee_USDamount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filing_fee_PHPamount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.accountsreceivable')),
                ('pfdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.bills')),
            ],
        ),
    ]
