# Generated by Django 4.2.6 on 2024-01-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='pf_amount',
            new_name='pf_PhPamount',
        ),
        migrations.AddField(
            model_name='bills',
            name='pf_USDamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='taskcode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ope',
            name='exp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ope',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
