# Generated by Django 4.2.6 on 2024-01-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_pf_amount_bills_pf_phpamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceImage', models.ImageField(blank=True, null=True, upload_to='invoices/%Y/')),
                ('ar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.accountsreceivable')),
            ],
        ),
    ]
