# Generated by Django 4.2.6 on 2024-10-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_tempope_phpamount_alter_tempope_usdamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsreceivable',
            options={'verbose_name_plural': 'Clients Accounts Recievable'},
        ),
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name_plural': 'Professional Services Rendered'},
        ),
        migrations.AlterModelOptions(
            name='filingfees',
            options={'verbose_name_plural': 'Govt/Filing Fees'},
        ),
        migrations.AlterModelOptions(
            name='invoiceimage',
            options={'verbose_name_plural': 'Physical Invoice'},
        ),
        migrations.AlterModelOptions(
            name='ope',
            options={'verbose_name_plural': 'OPE'},
        ),
        migrations.AlterModelOptions(
            name='tempbills',
            options={'verbose_name_plural': 'Proforma Services Rendered'},
        ),
        migrations.AlterModelOptions(
            name='tempfilingfees',
            options={'verbose_name_plural': 'Proforma Filing Fees'},
        ),
        migrations.AlterModelOptions(
            name='tempope',
            options={'verbose_name_plural': 'Proforma Expenses'},
        ),
    ]
